controller_manager:
  ros__parameters:
    update_rate: 50 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    steering_joints_names:
      - front_right_steer_joint
      - front_left_steer_joint
    traction_joints_names:
      - rear_right_wheel_joint
      - rear_left_wheel_joint

    # Kinematics Calibration
    wheelbase: 0.24        # Distance between front and rear axles
    traction_track_width: 0.18
    steering_track_width: 0.18
    traction_wheels_radius: 0.033

    # Odometry Configuration
    position_feedback: true # Use joint encoder feedback to compute odom
    open_loop: false        # False means it calculates odometry from encoder state feedback

    # Frames
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true

    reference_timeout: 2.0